In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.6109, 0.1437, 0.9656],
        [0.7427, 0.9171, 0.6551],
        [0.2444, 0.1944, 0.8742],
        [0.3132, 0.5923, 0.3605],
        [0.8052, 0.0885, 0.6429]])


In [32]:
embedded = torch.tensor([[1,2,3],[4,5,6]], dtype=float)
torch.mean(embedded, dim=0)

tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64)

In [30]:
label = 2
torch.LongTensor(label)


tensor([0, 0])

In [10]:
torch.empty(3, dtype=torch.long).random_(5)

tensor([2, 1, 0])